language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
cache: ccache
script:
- cd StackExchange.Redis.ConnectionPool
- dotnet restore
- dotnet build -c Release
- dotnet pack -c Release -o $PWD
- dotnet nuget push ./*.nupkg -k $nugetKey -s https://www.nuget.org/api/v2/package